gunicorn:
    bind: "[::]:8003"
    workers: 2
    threads: 4
    timeout: 120
    log_file: "/tmp/lens3-gunicorn-adm-log"
    log_level: debug
    log_syslog_facility: LOCAL7
    reload: yes

redis:
    host: localhost
    port: 6379
    password: ZXjmrOLwQ8Ri51pb5FI79z51gAHfIQ4oMvtWrG8q

lenticularis:

    multiplexer:
        delegate_hostname: lens3.example.jp

    controller:
        max_lock_duration: 60

    system_settings:
        max_zone_per_user: 3
        max_direct_hostnames_per_user: 2
        default_zone_lifetime: 630720000
        allowed_maximum_zone_exp_date: 2279404800
        endpoint_url: https://{hostname}/
        direct_hostname_validator: flat
        direct_hostname_domain: s3.lens3.example.jp
        reserved_hostnames:
            - bad.lens3.example.jp
        decoy_connection_timeout: 60

    log_file: "/tmp/lens3-adm-log"
    log_syslog:
        facility: LOCAL7
        priority: DEBUG

webui:
    trusted_proxies:
        - localhost
    CSRF_secret_key: xyzzy
