#! /bin/sh
#set -o xtrace
set -o errexit
set -o nounset
#set -o pipefail

. ./subr
. ./config

crate_daemon_owner \
	$daemon_owner \
	$daemon_owner_group

id $admin_user >/dev/null 2>/dev/null ||
	sudo useradd -m -U $admin_user
sudo usermod -a -G $daemon_owner_group $admin_user

install_requirements_for_user $admin_user $srcdir
install_requirements_for_user $daemon_owner $srcdir

[ -f $adm_config ] ||
	(sudo mkdir -p $conf_file_dir &&
	 sudo cp $srcdir/webui/adm-config.yaml.in $adm_config &&
	 sudo chown $daemon_owner:$daemon_owner_group $adm_config &&
	 sudo chmod 440 $adm_config)
sudo diff -uw examples/adm-config.yaml $adm_config || true
cppe examples/adm-config.yaml $adm_config
ls -l $adm_config

[ -f $api_unit_file ] ||
	sudo cp $srcdir/webui/lenticularis-api.service.in $api_unit_file
sudo diff -uw examples/lenticularis-api.service $api_unit_file || true
cppe examples/lenticularis-api.service $api_unit_file
ls -l $api_unit_file

sudo systemctl stop $api_service_name
sudo systemctl enable $api_service_name
sudo systemctl start $api_service_name
sleep 3
systemctl status $api_service_name

ps xa|egrep '([g]unicorn)'
netstat -an|grep '\<8001\>.*LISTEN'

echo DONE $(date '+%Y-%m-%dT%H:%M:%S.%6N%:z') 1>&2
