#! /bin/sh

#set -o xtrace
set -o errexit
set -o nounset
#set -o pipefail

sudo dnf -qq install -y unzip

awscli_dist=https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
aws_bindir=/opt/bin
aws_installdir=/opt/aws-cli

tmpdir=$(mktemp -d)
(
	cd $tmpdir &&
	curl -s $awscli_dist > awscliv2.zip &&
	unzip -qq awscliv2.zip &&
	sudo ./aws/install --bin-dir $aws_bindir --install-dir $aws_installdir --update
)
rm -rf $tmpdir
pip3 -qq install -r requirements.txt --user

#lenticularis-admin show allow-deny-rules
#lenticularis-admin show user-info
#lenticularis-admin show zone
#lenticularis-admin show multiplexer
#lenticularis-admin show server-processes
#lenticularis-admin show routing-table

echo DONE $(date '+%Y-%m-%dT%H:%M:%S.%6N%:z') 1>&2
