#! /bin/sh

#set -o xtrace
set -o errexit
set -o nounset
#set -o pipefail

. ./config

for i in $(seq 0 $((nusers - 1))); do
	name=$(printf u%04d $i)
	group=$(printf u%04d $i)
	id $name >/dev/null 2>/dev/null ||
		sudo useradd -m -U $name
done

id u0000

echo DONE $(date '+%Y-%m-%dT%H:%M:%S.%6N%:z') 1>&2
