all::
	@echo "Targets:"
	@echo "1. common:            Install Common Packages"
	@echo "2. hosts:             /etc/hosts"
	@echo "3. disable_firewall:  Disable Firewall and SELinux"
	@echo "4  redis:             Setup Redis"
	@echo "5. reverseproxy:      Setup Reverse Proxy (NGINX)"
	@echo "6. admin:             Install Administrator and API"
	@echo "7. multiplexer:       Install Multiplexer"
	@echo "8. create_users:      Create User"
	@echo "9. uinfo:             Create User"
	@echo "-. nfs_and_nis:       Setup NFS and NIS"

admin::
	./$@

common::
	./$@

disable_firewall::
	./$@

reverseproxy::
	./$@

hosts::
	./$@

multiplexer::
	./$@

nfs_and_nis::
	./$@

redis::
	./$@

create_users::
	./$@

uinfo::
	./$@

