#! /bin/sh

#set -o xtrace
set -o errexit
set -o nounset
#set -o pipefail

. ./subr
. ./config

crate_daemon_owner \
	$daemon_owner \
	$daemon_owner_group

if [ ! -f $minio_bin ]; then
	tmpdir=$(mktemp -d)
	curl https://dl.min.io/server/minio/release/linux-amd64/minio > $tmpdir/minio
	sudo install -m 755 -c $tmpdir/minio $minio_bin
	rm -f $tmpdir/minio
	rmdir $tmpdir
fi

if [ ! -f $mc_bin ]; then
	tmpdir=$(mktemp -d)
	curl https://dl.min.io/client/mc/release/linux-amd64/mc > $tmpdir/mc
	sudo install -m 755 -c $tmpdir/mc $mc_bin
	rm -f $tmpdir/mc
	rmdir $tmpdir
fi

install_requirements_for_user $daemon_owner $srcdir

#getent group minio ||
#	sudo groupadd minio

sudo [ -e /etc/sudoers.d/lenticularis ] ||
cat <<-EOF | sudo dd of=/etc/sudoers.d/lenticularis 2>/dev/null
	Defaults env_keep += "MINIO_ROOT_USER MINIO_ROOT_PASSWORD MINIO_HTTP_TRACE MINIO_BROWSER"
	$daemon_owner	ALL=(ALL, !root)	NOPASSWD: $minio_bin
EOF

[ -f $mux_config ] ||
	(sudo mkdir -p $conf_file_dir &&
	 sudo cp $srcdir/multiplexer/mux-config.yaml.in $mux_config &&
	 sudo chown $daemon_owner:$daemon_owner_group $mux_config &&
	 sudo chmod 440 $mux_config)
sudo diff -uw examples/mux-config.yaml $mux_config || true
cppe examples/mux-config.yaml $mux_config
ls -l $mux_config

[ -f $mux_unit_file ] ||
	sudo cp $srcdir/multiplexer/lenticularis-mux.service.in $mux_unit_file
sudo diff -uw examples/lenticularis-mux.service $mux_unit_file || true
cppe examples/lenticularis-mux.service $mux_unit_file
ls -l $mux_unit_file

sudo systemctl stop $mux_service_name
sudo systemctl enable $mux_service_name
sudo systemctl start $mux_service_name
sleep 3
systemctl status $mux_service_name

ps xa|egrep '([g]unicorn)'
netstat -an|grep '\<8000\>.*LISTEN'

echo DONE $(date '+%Y-%m-%dT%H:%M:%S.%6N%:z') 1>&2
