#! /bin/sh

#set -o xtrace
set -o errexit
set -o nounset
#set -o pipefail

. ./subr
. ./config

sudo dnf -qq install -y redis

sudo systemctl stop redis

sudo diff -uw examples/redis.conf $redis_conf || true
sudo sed -i -e '/^bind/s/^/#/' -e '/# requirepass/s/.*/requirepass deadbeef/' /etc/redis.conf

sudo systemctl start redis
sudo systemctl enable redis
sleep 3
systemctl status redis

ps xa|egrep '([r]edis)'
netstat -an|grep '\<6379\>.*LISTEN'

echo DONE $(date '+%Y-%m-%dT%H:%M:%S.%6N%:z') 1>&2
