#! /bin/sh

#set -o xtrace
set -o errexit
set -o nounset
#set -o pipefail

. ./config

tmpfile=$(mktemp)
(for i in $(seq 0 $((nusers - 1))); do
	name=$(printf u%04d $i)
	group=$(printf u%04d $i)
	echo $name,$group
done) > $tmpfile

tail $tmpfile

#set -o xtrace

lenticularis-admin insert user-info $tmpfile
rm $tmpfile
lenticularis-admin show user-info | sort | tail

tmpfile=$(mktemp)
cat <<EOF > $tmpfile
allow,*
EOF

head $tmpfile

lenticularis-admin insert allow-deny-rules $tmpfile
rm $tmpfile
lenticularis-admin show allow-deny-rules --format=json

echo DONE $(date '+%Y-%m-%dT%H:%M:%S.%6N%:z') 1>&2
