## makefile

all::
	@echo Run make build

build::
	go build

fmt::
	go fmt

get::
	go get github.com/aws/aws-sdk-go-v2/aws
	go get github.com/aws/aws-sdk-go-v2/config
	go get github.com/aws/aws-sdk-go-v2/credentials
	go get github.com/aws/aws-sdk-go-v2/service/s3

init::
	go mod init sporadic
