gunicorn:
    bind: "[::]:8001"
    workers: 24
    timeout: 120
    log_syslog_facility: LOCAL7
    reload: yes


redis:
    host: localhost
    port: 6379
    password: deadbeef


lenticularis:

    multiplexer:
        delegate_hostname: lent8.example.com

    controller:
        max_lock_duration: 60

    system_settings:
        max_zone_per_user: 3
        max_direct_hostnames_per_user: 2
        default_zone_lifetime: 630720000
        allowed_maximum_zone_exp_date: 2279404800
        endpoint_url: https://{hostname}/
        direct_hostname_validator: flat
        direct_hostname_domain: lent8.example.com
        reserved_hostnames:
            - webui.lent8.example.com
        decoy_connection_timeout: 60

    syslog:
        facility: LOCAL7
        priority: DEBUG


webui:
    trusted_proxies:
        - localhost
    CSRF_secret_key: deadbeef
