gunicorn:
    bind: "[::]:8000"
    workers: 2
    threads: 40
    timeout: 60
    log_syslog_facility: LOCAL7
    reload: yes
    

redis:
    host: localhost
    port: 6379
    password: deadbeef


lenticularis:

    multiplexer:
        port: 8000
        delegate_hostname: lent8.example.com
        trusted_proxies:
            - localhost
        timer_interval: 30
        request_timeout: 60

    controller:
        port_min: 9000
        port_max: 18999
        watch_interval: 30
        keepalive_limit: 600
        allowed_down_count: 3
        max_lock_duration: 60
        mc_info_timelimit: 20
        mc_stop_timelimit: 20
        kill_supervisor_wait: 60
        minio_user_install_timelimit: 60
        refresh_margin: 5
        sudo: /usr/bin/sudo

    minio:
        minio: /usr/local/bin/minio
        minio_http_trace: /var/log/minio_http_trace
        mc: /usr/local/bin/mc

    syslog:
        facility: LOCAL7
        priority: DEBUG
