redis:
    host: localhost
    port: 6378
    password: ZXjmrOLwQ8Ri51pb5FI79z51gAHfIQ4oMvtWrG8q

gunicorn:
    port: 8003
    workers: 2
    timeout: 120
    access_logfile: "/var/tmp/lenticularis/lens3-gunicorn-api-access-log"
    log_file: "/var/tmp/lenticularis/lens3-gunicorn-api-log"
    log_level: debug
    #log_syslog_facility: LOCAL8
    reload: yes

aws_signature: "AWS4-HMAC-SHA256"

multiplexer:
    facade_hostname: fgkvm-010-128-008-026.fdcs.r-ccs.riken.jp
    probe_access_timeout: 60

minio_manager:
    minio_mc_timeout: 10

minio:
    minio: /home/lens3/bin/minio
    mc: /home/lens3/bin/mc

system:
    trusted_proxies:
        - localhost
    max_pool_expiry: 630720000
    CSRF_secret_key: xyzzy

log_file: "/var/tmp/lenticularis/lens3-api-log"
log_syslog:
    facility: LOCAL7
    priority: DEBUG
