#!/bin/ksh -x

# Fixes the files generated by "build".  It inserts a base-path
# setting code in the "index.html".

f=../src/lenticularis/ui/index.html
if grep PLACE_BASE_PATH_SETTING_HERE $f > /dev/null; then
    echo "$0: Fix already applied."
    exit 0
fi
sed -e 's|="/assets/|="./assets/|g' \
    -e 's|^  <div id="app"></div>$|  <div id="app"></div>\n  PLACE_BASE_PATH_SETTING_HERE|' < $f > xxx
mv xxx $f
