all::
	@echo "Targets:"
	@echo "  create  -- create containers defined in 'config'"
	@echo "  start   -- start all containers"
	@echo "  stop    -- stop all containers"
	@echo "  drop    -- drop all containers"
	@echo "  list    -- list containers"
	@echo "  install -- install lenticularis into container that defined in 'config'"

drop::
	./$@

stop::
	./$@

start::
	./$@

create::
	./$@

list::
	lxc ls

install::
	./create install_lenticularis
