# makefile

all::

go::
	go build sporadic.go

goinit::
	go mod init sporadic

goget::
	go get github.com/aws/aws-sdk-go-v2/aws
	go get github.com/aws/aws-sdk-go-v2/config
	go get github.com/aws/aws-sdk-go-v2/service/s3
	go get github.com/aws/aws-sdk-go-v2/credentials
